spring.datasource.url=jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

langchain4j.anthropic.chat-model.api-key=${ANTHROPIC_API_KEY}
langchain4j.anthropic.chat-model.model-name=claude-haiku-4-5-20251001
langchain4j.anthropic.chat-model.top-k=30
langchain4j.anthropic.chat-model.max-tokens=512
langchain4j.anthropic.chat-model.cache-system-messages=true
langchain4j.anthropic.chat-model.cache-tools=true
langchain4j.anthropic.chat-model.log-requests=true
langchain4j.anthropic.chat-model.log-responses=true

evolution.instance-name=fluencia
url.send-text=${URL_SEND_TEXT}
